//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adre
    {
        public int AdresID { get; set; }
        public int MusteriID { get; set; }
        public string Adress { get; set; }
        public string Ilce { get; set; }
        public string Il { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
